### ISSUE TITLE
Clang/OpenMP contributions

### ISSUE THREAD

**Issue by chris-wood** [clang-omp/clang#12]
I'm interested in contributing to this project, though the documentation and open issues about where and how to get started are quite minimal. In particular, I would like to help develop new optimization passes or improve the existing Clang support for OpenMP. If you could provide some information about how to accomplish either one of these tasks (e.g. where in the code to look), that would be great!

**Comment by clang-omp** [comment]
Hi Chris.
Thank you for attention. We appreciate your willingness to help in the development of OpenMP support in Clang. The main trouble with the current implementation is that it is just a temporary solution and it will be reworked. That's why there is no any documentation for the current implementation.
But we have one common issue, which need to be solved - capturing variables with variable-length array type.
For example, currently the following test does cannot be compiled by clang:

``` c
#include <stdio.h>
int main(int argc, char **argv) {
  int vla[argc+10];
  vla[argc] = 103;
#pragma omp parallel firstprivate(vla)
  printf("%d", vla[argc]);
  return 0;
}
```

```
$ clang -fopenmp test.c

test.c:6:16: error: variable 'vla' with variably modified type cannot be captured
  printf("%d", vla[argc]);
               ^
test.c:3:7: note: 'vla' declared here
  int vla[argc+10];
      ^
test.c:5:37: error: variable 'vla' with variably modified type cannot be captured
  #pragma omp parallel firstprivate(vla)
                                    ^
test.c:3:7: note: 'vla' declared here
  int vla[argc+10];
      ^
2 errors generated.
$
```

Currently clang generates error message, though actually the code is correct. Clang should be able to compile and execute this code.
If you are interested in this work we can give some additional info on where to start to dig.

GL
