### ISSUE TITLE
Will this work for iOS?

### ISSUE THREAD

**Issue by JetForMe** [clang-omp/clang#18]
iOS doesn't allow the use of dynamically-linked libraries in submitted apps. Is it possible to link the runtime statically?

**Comment by jcownie-intel** [comment]
The OpenMP\* runtime library can be built statically (for instance we ship a static library with our commercial compilers on Linux/X86).
However, since I haven't been involved in the ARM/iOS port I have no idea what that does, or whether it even exists!
(There's a separate whole discussion to be had about the sanity of using the OpenMP programming model on a phone/tablet which is  a _very_ different environment from the supercomputers for which OpenMP was developed, but that's probably not for now!)

**Comment by JetForMe** [comment]
Thanks for the reply. In some simple cases, we replaced our OpenMP code with GCD calls, and saw improvements. But it would be better if we could get full-up OpenMP support. Thanks!
