### ISSUE TITLE
template captured var

### ISSUE THREAD

**Issue by pbrunet** [clang-omp/clang#29]
Hi,

I am working on some templated code and I don't succeed to get captured var.
I used to iterate through capture_begin(), capture_end() from the captured statement but it looks empty in template function. Is there another interface specific for templates?

Best,
Pierrick

**Comment by alexey-bataev** [comment]
Hi Pierrick,
Could you send me some small example and point to variable which you 
want to find in list of captures?

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

7 Апрель 2014 г. 17:33:29, pbrunet писал:

**Comment by pbrunet** [comment]
```
#include <iostream>

template<class T>
int lala(T a)
{
    int b;
#pragma omp parallel
#pragma omp single
#pragma omp task
   std::cout << a << "/" << b << std::endl;
}

int main()
{
    lala(12);
    return 0;
}
```

Here is an example. neither `a` or `b` are captured in this case.

Pierrick

**Comment by alexey-bataev** [comment]
Hi Pierrick,
Sorry for the delay with the answer.
For template functions variables are captured automatically on 
instantiation. There is nothing to capture in templates, because 
variables are not variables actually, but templates.

Best regards,

# Alexey Bataev

Software Engineer
Intel Compiler Team
Intel Corp.

8 Апрель 2014 г. 11:32:32, pbrunet писал:
